#!/usr/bin/env python

__license__ = 'GPLv3'

__author__ = 'haxwithaxe <me@haxwithaxe.net>'

import json
import sys
import os

HEADER = '// generated by %s from %s
#include "keypress.h"'

base_list = []
for i in range(0,256):
	base_list += ['\t0,']

def arr2int(*arr):
	mask = 1
	return (((arr[7]&mask)<<7)|((arr[6]&mask)<<6)|((arr[5]&mask)<<5)|((arr[4]&mask)<<4)|((arr[3]&mask)<<3)|((arr[2]&mask)<<2)|((arr[1]&mask)<<1)|arr[0]&mask)

modkey_scancodes = [0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80]
key_array = '''	%(vals)s, // %(name)s; %(comment)s'''
cases = ''

OUT=open('keymap.h','w')
file_list_str = ', '.join(sys.argv[1:])
outstr = (HEADER % (sys.argv[0],file_list_str))+'''
unint8_t hashpins(int arr[8])
{
	uint8_t hash = 0;
	for(int i=7;i>=0;i--)
	{
		hash = hash | ((arr[i]&mask)<<i);
	}
	retutn hash;
}
uint8_t modkeys[8] = {
		0x01,
		0x02,
		0x04,
		0x08,
		0x10,
		0x20,
		0x40,
		0x80
	};

'''

for file_name in sys.argv[1:]:
	IN=open(file_name,'r')

	confdict = json.loads(IN.read())
	IN.close()

	keymap_str = '''KeyPress keymap_%(map_name)s[256] = {
%(list)s
	};
'''

	for key, val in confdict.items():
			k = val['keys']
			while len(k) < 8:
				k+=[0]
			btn_hash = arr2int(*k)
			keys_list = 'KeyPress::Keypress(%s, %s, %s)' % ( btn_hash, val['keysym'], 0)
			base_list[btn_hash] = key_array % {'vals':keys_list,'name':val['name'],'comment':val['comment']}

	cases = '\n'.join(base_list)

	outstr += keymap_str % {'list':cases,'map_name':os.path.split(file_name)[-1].replace('.map','').replace('.json','')}

OUT.write(outstr)
