#!/usr/bin/env python

import json
import sys
import os

HEADER = '// generated by %s from %s'

base_list = []
for i in range(0,256):
	base_list += ['\t0,']

modkey_scancodes = [0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80]
key_array = '''	%(vals)s, // %(name)s; %(comment)s'''
cases = ''

OUT=open('keymap.h','w')
file_list_str = ', '.join(sys.argv[1:])
outstr = (HEADER % (sys.argv[0],file_list_str))+'''
uint8_t modkeys[8] = {0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80};
'''

for file_name in sys.argv[1:]:
	IN=open(file_name,'r')

	confdict = json.loads(IN.read())
	IN.close()

	keymap_str = '''uint8_t keymap_%(map_name)s[256] = {
%(list)s
	};
'''

	for key, val in confdict.items():
			k = val['keys']
			while len(k) < 8: k+=[0]
			mask = 1
			btn_hash = (((k[7]&mask)<<7)|((k[6]&mask)<<6)|((k[5]&mask)<<5)|((k[4]&mask)<<4)|((k[3]&mask)<<3)|((k[2]&mask)<<2)|((k[1]&mask)<<1)|k[0]&mask)
			keys_list = '%s' % val['keysym']
			base_list[btn_hash] = key_array % {'vals':keys_list,'name':val['name'],'comment':val['comment']}

	cases = '\n'.join(base_list)

	outstr += keymap_str % {'list':cases,'map_name':os.path.split(file_name)[-1].replace('.map','').replace('.json','')}

OUT.write(outstr)
